defaults:
  - base_config
  - db: mysql
  - override hydra/help: my_app_help
  # See composition order note
  - _self_

debug: true
hydra:
  output_subdir: null  # hydra 配置文件的输出目录
  run:
    dir: logs/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}  # 日志文件的输出目录
